"""
firmware_flasher.py
Automates: CA header export → PlatformIO build → flash → reboot wait.

Called by main.py before experiments start (when AUTO_FLASH = True).
WiFi credentials and SERVER_IP are injected as PlatformIO build flags
so main.cpp never needs manual editing.

Key design decisions
────────────────────
* A SHA-256 hash of (ca_pem + wifi_ssid + server_ip + firmware_version)
  is written to esp32/.flash_hash.  Re-flash is skipped when the hash
  matches, saving ~30 s per run when nothing changed.
* pio is invoked as a subprocess; stdout/stderr are streamed live so the
  user sees compile progress.
* After upload, the serial port is opened briefly to drain boot messages
  and confirm "READY" before returning control to main.py.
"""

import hashlib, json, logging, shutil, subprocess, sys, time
from pathlib import Path
from typing import Optional

log = logging.getLogger("flasher")

ESP32_DIR  = Path("esp32")
HASH_FILE  = ESP32_DIR / ".flash_hash"
HEADER_DST = ESP32_DIR / "src" / "root_ca_embed.h"


# ── CA header ────────────────────────────────────────────

def write_ca_header(ca_pem: str) -> None:
    """Write/overwrite root_ca_embed.h with the supplied PEM.

    IMPORTANT: The raw string R"(...)" must start DIRECTLY with
    '-----BEGIN CERTIFICATE-----' – no leading newline.  mbedTLS's
    PEM parser scans from the very first byte, so a leading \n
    causes it to silently fail and treat the CA as empty, producing
    MBEDTLS_ERR_X509_CERT_VERIFY_FAILED (-9984) at handshake time.
    """
    HEADER_DST.parent.mkdir(parents=True, exist_ok=True)
    pem = ca_pem.strip()   # strip ALL leading/trailing whitespace

    # Sanity-check before writing
    if not pem.startswith("-----BEGIN CERTIFICATE-----"):
        raise ValueError(
            "[Flasher] CA PEM does not start with expected header. "
            f"First 40 chars: {repr(pem[:40])}"
        )

    # ROOT_CA_PEM[0] must be '-', NOT '\n'.
    # We build the line as a regular string (not an f-string with backslash)
    # to avoid the leading-newline trap.
    opening = 'static const char ROOT_CA_PEM[] = R"('
    closing = ')\";'
    content = (
        "// Auto-generated by firmware_flasher.py – do not edit.\n"
        "// Regenerated before every flash when the CA changes.\n\n"
        + opening + pem + "\n" + closing + "\n"
    )
    HEADER_DST.write_text(content)

    # Verify the written file is correct
    written = HEADER_DST.read_text()
    marker = 'R"(-----BEGIN CERTIFICATE-----'
    if marker not in written:
        raise RuntimeError(
            f"[Flasher] BUG: header written but '{marker}' not found. "
            "Check write_ca_header logic."
        )
    log.info(f"[Flasher] CA header written → {HEADER_DST}")


# ── Hash / cache ──────────────────────────────────────────

def _compute_hash(ca_pem: str, ssid: str, server_ip: str, fw_version: str) -> str:
    blob = "\n".join([ca_pem, ssid, server_ip, fw_version])
    return hashlib.sha256(blob.encode()).hexdigest()


def _cached_hash() -> str:
    if HASH_FILE.exists():
        return HASH_FILE.read_text().strip()
    return ""


def _save_hash(h: str) -> None:
    HASH_FILE.write_text(h)


# ── PlatformIO helpers ────────────────────────────────────

def _pio_available() -> bool:
    return shutil.which("pio") is not None


def _run_pio(*args) -> bool:
    """Run a pio command inside esp32/; stream output; return success."""
    cmd = ["pio"] + list(args)
    log.info(f"[Flasher] $ {' '.join(cmd)}")
    proc = subprocess.Popen(
        cmd,
        cwd=str(ESP32_DIR),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    for line in proc.stdout:
        line = line.rstrip()
        if line:
            log.info(f"  [pio] {line}")
    proc.wait()
    return proc.returncode == 0


def _inject_build_flags(ssid: str, password: str, server_ip: str) -> None:
    """
    Patch platformio.ini build_flags to inject WiFi + server credentials.
    We rewrite only the flag lines; the rest of the file is preserved.
    """
    ini_path = ESP32_DIR / "platformio.ini"
    text = ini_path.read_text()

    # Remove previous injected flags block if present
    marker_start = "; == AUTO-INJECTED START ==\n"
    marker_end   = "; == AUTO-INJECTED END ==\n"
    if marker_start in text:
        s = text.index(marker_start)
        e = text.index(marker_end) + len(marker_end)
        text = text[:s] + text[e:]

    # Build the new flags block
    injected = (
        f"{marker_start}"
        f"    -DWIFI_SSID='\"{ssid}\"'\n"
        f"    -DWIFI_PASSWORD='\"{password}\"'\n"
        f"    -DSERVER_IP='\"{server_ip}\"'\n"
        f"{marker_end}"
    )

    # Insert after the existing build_flags = line
    if "build_flags =" in text:
        idx = text.index("build_flags =") + len("build_flags =\n")
        text = text[:idx] + injected + text[idx:]
    else:
        text += f"\nbuild_flags =\n{injected}"

    ini_path.write_text(text)
    log.info("[Flasher] platformio.ini patched with WiFi + server credentials")


# ── Reboot wait ───────────────────────────────────────────

def _wait_for_ready(port: str, baudrate: int, timeout: int = 60) -> bool:
    """
    Open the serial port and wait for the 'READY' JSON heartbeat.
    Returns True on success, False on timeout.
    """
    try:
        import serial as _serial
    except ImportError:
        log.warning("[Flasher] pyserial not installed; skipping reboot wait")
        time.sleep(5)
        return True

    deadline = time.time() + timeout
    log.info(f"[Flasher] Waiting for ESP32 READY on {port} (up to {timeout}s)…")
    # The port may not be available immediately after flash
    ser = None
    while time.time() < deadline:
        try:
            ser = _serial.Serial(port, baudrate, timeout=1)
            break
        except Exception:
            time.sleep(1)
    if ser is None:
        log.error("[Flasher] Could not reopen serial port after flash")
        return False

    try:
        while time.time() < deadline:
            raw = ser.readline().decode(errors="ignore").strip()
            if not raw:
                continue
            log.debug(f"[ESP32-boot] {raw}")
            # Accept both old "READY" string and new JSON heartbeat
            if raw == "READY" or (raw.startswith("{") and '"type":"heartbeat"' in raw):
                log.info("[Flasher] ESP32 is READY")
                return True
    finally:
        ser.close()

    log.warning("[Flasher] Timed out waiting for ESP32 READY")
    return False


# ── Public API ────────────────────────────────────────────

def flash_if_needed(
    ca_pem: str,
    ssid: str,
    password: str,
    server_ip: str,
    serial_port: str,
    baudrate: int,
    fw_version: str,
    force: bool = False,
) -> bool:
    """
    Main entry point called by main.py.

    1. Compute hash of (ca_pem + ssid + server_ip + fw_version).
    2. If hash matches cached hash AND not forced → skip flash.
    3. Otherwise: write CA header, patch ini, pio build, pio upload, wait READY.
    4. Return True if firmware is ready (flashed or cache-hit).
    """
    if not _pio_available():
        log.warning("[Flasher] pio not found on PATH – skipping auto-flash. "
                    "Install PlatformIO or flash manually.")
        return False

    new_hash = _compute_hash(ca_pem, ssid, server_ip, fw_version)

    if not force and _cached_hash() == new_hash:
        log.info("[Flasher] Firmware hash matches – skipping re-flash ✓")
        return True

    log.info("[Flasher] ── Starting firmware build + flash ──────────────")
    write_ca_header(ca_pem)
    _inject_build_flags(ssid, password, server_ip)

    if not _run_pio("run", "--target", "upload"):
        log.error("[Flasher] PlatformIO build/upload FAILED")
        return False

    ok = _wait_for_ready(serial_port, baudrate)
    if ok:
        _save_hash(new_hash)
        log.info("[Flasher] Flash complete ✓")
    return ok