[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; mbedTLS heap is large – give it room
board_build.partitions = huge_app.csv

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=16384

lib_deps =

monitor_speed = 115200
upload_speed  = 115200
